services:
  - type: web
    name: maze-racer
    env: node
    plan: free
  # Change to `main` after you merge multiplayer.
    branch: multiplayer
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_VERSION
        value: "18"
